---
# Playbook to manage Datasources in Grafana
#
- name: "Manage Grafana Datasources"
  hosts: localhost
  tasks:
    - name: "Create DataSources"
      ansible.builtin.include_role:
        name: "grafana"
        tasks_from: "create_ds"
      vars:
        grafana_datasource_content: "{{ ds.value }}"
        grafana_datasource_name: "{{ ds.key }}"
      loop: "{{ grafana_datasources | dict2items}}"
      loop_control: 
        loop_var: "ds"
