---
# Playbook to start ApiMon Executors
#
- name: "Starting ApiMon Executors"
  hosts: "{{ executors_group_name }}:!disabled"
  become: true
  tasks:
    - name: Start apimon-executor
      ansible.builtin.service:
        name: "apimon-executor"
        state: "started"
