---
# Playbook to start ApiMon Schedulers
#
- name: "Starting ApiMon Schedulers"
  hosts: "{{ schedulers_group_name }}:!disabled"
  become: true
  tasks:
    - name: Start apimon-scheduler
      ansible.builtin.service:
        name: "apimon-scheduler"
        state: "started"
