---
# Playbook to stop ApiMon Schedulers
#
- name: "Stopping ApiMon Schedulers"
  hosts: "{{ schedulers_group_name }}:!disabled"
  become: true
  tasks:
    - name: Stop apimon-scheduler
      ansible.builtin.service:
        name: "apimon-scheduler"
        state: "stopped"
